-- Oracle 23ai Relational-Duality-View
-- based on race example

drop table if exists driver;
drop table if exists team;
drop view  if exists json23ai;

CREATE TABLE team
  (team_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   name    VARCHAR2(255) NOT NULL UNIQUE,
   points  INTEGER NOT NULL,
   CONSTRAINT team_pk PRIMARY KEY(team_id));

CREATE TABLE driver
  (driver_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   name      VARCHAR2(255) NOT NULL UNIQUE,
   points    INTEGER NOT NULL,
   team_id   INTEGER,
   CONSTRAINT driver_pk PRIMARY KEY(driver_id),
   CONSTRAINT driver_fk FOREIGN KEY(team_id) REFERENCES team(team_id));

CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW json23ai AS
  SELECT JSON {'_id'    : t.team_id,
               'name'   : t.name,
               'points' : t.points,
               'driver' :
                 [ SELECT JSON {'_id'      : d.driver_id,
                                'name'     : d.name,
                                'points'   : d.points WITH NOCHECK}
                     FROM driver d WITH INSERT UPDATE
                     WHERE d.team_id = t.team_id ]}
    FROM team t WITH INSERT UPDATE DELETE;

INSERT INTO json23ai VALUES ('{
                              "name"   : "Red Bull",
                              "points" : 0,
                              "driver" : [ {
                                            "name"     : "Max Verstappen",
                                            "points"   : 0},
                                           {
                                            "name"     : "Sergio Perez",
                                            "points"   : 0} ]}');

INSERT INTO json23ai VALUES ('{
                              "name"   : "Ferrari",
                              "points" : 0,
                              "driver" : [ {
                                            "name"     : "Charles Leclerc",
                                            "points"   : 0},
                                           {
                                            "name"     : "Carlos Sainz Jr",
                                            "points"   : 0} ]}');

INSERT INTO json23ai VALUES ('{
                              "name"   : "Mercedes",
                              "points" : 0,
                              "driver" : [ {                                            "name"     : "George Russell",
                                            "points"   : 0},
                                           {
                                            "name"     : "Lewis Hamilton",
                                            "points"   : 0} ]}');
commit;