-- Oracle23ai JSON-validate constrain

DROP TABLE IF EXISTS object23ai;

CREATE TABLE object23ai(
  object_id       INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  object_name     VARCHAR2(30) NOT NULL,
  data            JSON,
  CONSTRAINT object23ai_pk PRIMARY KEY (object_id)
);

ALTER TABLE object23ai ADD CONSTRAINT object23ai_ck_1 check (data is json validate q'[{
  "type"       : "object",
  "properties" : {"fruit"    : {"type"      : "string",
                                "minLength" : 1,
                                "maxLength" : 10},
                  "quantity" : {"type"      : "number",
                                "minimum"   : 0,
                                "maximum"   : 100},
                  "orderdate": {"type": "string",
                                "default": "NOW",
                                "format": "date"}
  },
  "required"   : ["fruit", "quantity"]
}]');


Insert into UWE.OBJECT23AI (OBJECT_NAME,DATA) values ('bananas','{"fruit":"banana","quantity":12,"orderdate":"2024-08-23"}');
Insert into UWE.OBJECT23AI (OBJECT_NAME,DATA) values ('apples','{"fruit":"apples","quantity":10,"orderdate":"2024-08-23"}');
COMMIT;