-- drop table validate_json;
CREATE TABLE validate_json(
  id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(100) NOT NULL,
  data JSON,
  CONSTRAINT validate_json_pk PRIMARY KEY(id),
  CONSTRAINT validate_json_un UNIQUE(name)
);

-------------VALIDATE-CONSTRAINT -------------------------------------------------------------------
--ALTER TABLE validate_json DROP CONSTRAINT validate_json_validate;

ALTER TABLE validate_json ADD CONSTRAINT validate_json_validate CHECK (data IS JSON VALIDATE q'[{
  "type"       : "object",
  "properties" : {
    "lastname":  {"type": "string"},
    "firstname": {"type": "string"},
    "birthdate": {"type": "string", "format": "date"},
    "interests": {
      "type": "array",
      "items": {
        "type": "string", "enum": ["Computer", "Travel", "Sports", "Music", "Reading"]
      }
    },
    "addresses":   {
      "type": "array",
      "items": {
        "type": "object",
        "properties":{
          "address_type": {"type": "string", "enum": ["Office", "Private", "Billing", "Delivery"]},
          "country":      {"type": "string"},
          "city":         {"type": "string"},
          "street":       {"type": "string"}
        },
        "required": ["country", "city"]
      }
    }
  },
  "required"   : ["lastname"]
}]');

--------------------------------------------------------------------------------

DELETE FROM validate_json;
INSERT INTO validate_json(name, data) values('uwe', q'[
{
  "lastname": "Simon",
  "firstname": "Uwe",
  "addresses": [
    { "address_type": "Office", "country": "Germany", "city": "Cologne"},
    { "address_type": "Delivery", "country": "Germany", "city": "Cologne"},
  ],
  "interests": ["Computer", "Travel"]
}]');

INSERT INTO validate_json(name, data) values('james', q'[
{
  "lastname": "Bond",
  "firstname": "James",
  "addresses": [
    { "address_type": "Delivery", "country": "United Kingdom", "zip": "SE1 7TP", "city": "London", "street": "85 Albert Embankment"}
  ],
  "interests": ["Travel"]
}]');

COMMIT;

--------------------------------------------------------------------------------
-- duality view
CREATE TABLE customer(
  customer_id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  lastname     VARCHAR2(100) NOT NULL,
  firstname    VARCHAR2(100),
  birthdate     DATE,
  CONSTRAINT customer_pk PRIMARY KEY(customer_id)
);

CREATE TABLE address(
  address_id    INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id   INTEGER NOT NULL,
  address_type  VARCHAR(10) CHECK (address_type in ('Private', 'Office', 'Billing', 'Delivery')),
  country       VARCHAR2(60) NOT NULL,
  zip           VARCHAR2(20) NOT NULL,
  city          VARCHAR2(60) NOT NULL,
  street        VARCHAR2(60) NOT NULL,
  CONSTRAINT address_pk PRIMARY KEY(address_id),
  CONSTRAINT address_fk1 FOREIGN KEY(customer_id) REFERENCES customer
);


CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW duality_json AS
  SELECT JSON { '_id'        : c.customer_id,
                'lastname'   : c.lastname,
                'firstname'  : c.firstname,
                'adresses' :
                  [ SELECT JSON {'_id'         : a.address_id,
                                'address_type' : a.address_type WITH NOCHECK,
                                'country'      : a.country      WITH NOCHECK,
                                'zip'          : a.zip          WITH NOCHECK,
                                'city'         : a.city         WITH NOCHECK,
                                'street'       : a.street       WITH NOCHECK}
                     FROM address a WITH INSERT UPDATE DELETE
                     WHERE a.customer_id = c.customer_id 
                  ]
              }
    FROM customer c WITH INSERT UPDATE DELETE;

delete from duality_json;

insert into duality_json values(q'[
{ 
  "lastname":"Kennedy","firstname":"J.F.K.",
  "adresses":[{"address_type": "Office", "country": "USA", "zip": "20500", "city": "Washington", "street": "1600 Pennsylvania Avenue NW"}]
}
]');

insert into duality_json values(q'[
{ 
  "lastname":"Merkel","firstname":"Angela",
  "adresses":[{"address_type": "Office", "country": "Germany", "zip": "10557", "city": "Berlin", "street": "Willy-Brandt-Straße 1"}]
}
]');

insert into duality_json values(q'[
{ 
  "lastname":"Blair","firstname":"Tony",
  "adresses":[{"address_type": "Office", "country": "Germany", "zip": "SW1A 2AA", "city": "London", "street": "10 Downing St"}]
}
]');

insert into duality_json values(q'[
{ 
  "lastname":"Macron","firstname":"Emmanuel",
  "adresses":[{"address_type": "Office", "country": "France", "zip": "S75008", "city": "Paris", "street": "55 Rue du Faubourg Saint-Honoré"}]
}
]');

COMMIT;
