CREATE TABLE generate_json(
  id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(100) NOT NULL,
  data CLOB,
  CONSTRAINT generate_json_pk PRIMARY KEY(id),
  CONSTRAINT generate_json_un UNIQUE(name),
  CONSTRAINT generate_json_ck CHECK (data IS JSON)
);

CREATE TABLE fixed_json(
  id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name VARCHAR2(100) NOT NULL,
  data CLOB,
  CONSTRAINT fixed_json_pk PRIMARY KEY(id),
  CONSTRAINT fixed_json_un UNIQUE(name),
  CONSTRAINT fixed_json_ck CHECK (data IS JSON)
);

CREATE TABLE json_type(
  json_type_id  INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name          VARCHAR2(100) NOT NULL,
  json_schema   CLOB,
  CONSTRAINT json_type_pk PRIMARY KEY(json_type_id),
  CONSTRAINT json_type_un UNIQUE(name),
  CONSTRAINT json_type_ck CHECK (json_schema IS JSON)
);

CREATE TABLE variable_json(
  id   INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  json_type_id INTEGER NOT NULL,
  name VARCHAR2(100) NOT NULL,
  data CLOB,
  CONSTRAINT variable_json_pk PRIMARY KEY(id),
  CONSTRAINT variable_json_un UNIQUE(name),
  CONSTRAINT variable_json_ck CHECK (data IS JSON),
  CONSTRAINT variable_json_fk1 FOREIGN KEY(json_type_id) REFERENCES json_type
);

INSERT INTO json_type(name, json_schema) VALUES('Car', q'[{ 
  "type": "object",
  "required": ["brand", "model", "year"],
  "properties": {
    "brand":       {"type": "string"},
    "model":       {"type": "string"},
    "year":        {"type": "integer", "minimum":1885},
    "vintage_car": {"type": "boolean"},
    "engine":      {"type": "string", "enum": ["Electric", "Diesel", "Gasoline", "Premiunm gasoline"]},
    "power":       {"type": "integer", "minimum": 0, "apex":{"label": "power (KW)"}},
    "options": {
      "type": "array",
      "items": {
        "type": "string", "enum": ["air condition", "power stearing", "trailer hitch", "navi", "sound system", "4wd", "diff locks", "others"]
      } 
    }
  }
}]');

-- ------------ generate_json ------------------
INSERT INTO generate_json(name, data) VALUES ('James', q'[{
  "lastname": "Bond",
  "firstname": "James",
  "nickname": "007",
  "profession": "Secret agent",
}]');

INSERT INTO generate_json(name, data) VALUES ('Elisabeth', q'[{
  "lastname": "Windsor",
  "firstname": "Elisabeth II",
  "title": "Queen",
  "birthdate": "1926-04-21",
  "died_on": "2022-09-08",
  "Office": "Buckhingham Palace"
}]');

INSERT INTO generate_json(name, data) VALUES ('Athur', q'[{
  "lastname": "Conan Doyle",
  "firstname": "Arthur",
  "profession": "Detective",
  "birthdate": "1926-04-21",
  "died_on": "2022-09-08",
  "address": {
    "country": "United Kingdom",
    "zipcode": "NW1 6XE",
    "city": "London",
    "street": "Baker street 221b"
  }
}]');

-- ------------ fixed_json ------------------
INSERT INTO fixed_json(name, data) VALUES('Donald', q'[{
  "lastname":  "Duck",
  "firstname": "Donald",
  "birthdate": "",
  "address": {
    "city":    "Duckburg"
  }
}]');

INSERT INTO fixed_json(name, data) VALUES('Goofy', q'[{
  "lastname":  "Goof",
  "firstname": "Goofy",
  "birthdate": "1939-01-01",
  "address": {
    "city":    "Mouseton"
  }
}]');

INSERT INTO fixed_json(name, data) VALUES('Micky', q'[{
  "lastname":  "Mouse",
  "firstname": "Mickey",
  "address": {
    "city":    "Mouseton"
  }
}]');

INSERT INTO fixed_json(name, data) VALUES('Dagobert', q'[{
  "lastname":  "Duck",
  "firstname": "Dagobert",
  "address": {
    "city":    "Duckburg",
    "street":  "Killmotor Hill"
  },
  "creditcard": {
    "cardtype": "VISA",
    "number":   "1234 1234 1234 1234",
    "validity": "01/26"
  }
}]');

INSERT INTO fixed_json(name, data) VALUES('Queen', q'[{
  "title":     "Queen",
  "lastname":  "Windsor",
  "firstname": "Elisabeth II",
  "birthdate": "1926-04-21",
  "died_on":   "2022-09-08",
  "address": {
    "country": "United Kongdom",
    "zipcode": "SW1A 1AA",
    "city":    "London",
    "street":    "Buckingham Palace"
  }
}]');

-- ------------ json_type ------------------
INSERT INTO json_type(name, json_schema) VALUES('Truck', q'[{ 
  "type": "object",
  "required": ["brand", "model", "kind", "year", "axle_configuration"],
  "properties": {
    "brand":       {"type": "string"},
    "model":       {"type": "string"},
    "kind":        {"type": "string", "enum": ["", "Semi truck", "Dump truck", "Garbage truck", "Tanker truck", "delivery truck", "others"]},
    "year":        {"type": "integer", "minimum":1885},
    "axle_configuration": {"type": "string"},
    "power":       {"type": "integer", "minimum": 0, "apex":{"label": "power (KW)"}},
    "torque":      {"type": "integer", "apex": {"label": "Torque (NM)"}}
  }
}]');

-- ------------ variable_json ------------------
INSERT INTO variable_json(json_type_id, name, data) 
SELECT json_type_id, 'VW Golf', q'[{
  "brand": "Volkswagen",
  "model": "Golf",
  "year": 2023,
  "engine": "Diesel",
  "power": 120,
  "options": ["air condition", "powerstearing"]
}]'
FROM json_type WHERE name='Car';

INSERT INTO variable_json(json_type_id, name, data) 
SELECT json_type_id, 'Ford Explorer', q'[{
  "brand": "Ford",
  "model": "Explorer",
  "year": 2024,
  "engine": "Electric",
  "power": 120,
  "options": ["air condition", "powerstearing"]
}]'
FROM json_type WHERE name='Car';


INSERT INTO variable_json(json_type_id, name, data) 
SELECT json_type_id, 'Scania R440', q'[{
  "brand": "Scania",
  "model": "R440",
  "year": 2024,
  "engine": "Diesel",
  "kind": "Semi",
  "power": 410,
  "axle_configuration": "6x4"
}]'
FROM json_type WHERE name='Truck';

INSERT INTO variable_json(json_type_id, name, data) 
SELECT json_type_id, 'Volvo FH15', q'[{
  "brand": "Volvo",
  "model":  "GH15",
  "year":   2024,
  "engine": "Diesel",
  "power":  550,
  "kind": "Dump truck",
  "axle_configuration": "8x4"
}]'
FROM json_type WHERE name='Truck';

COMMIT;
