CREATE TABLE object23c(
  object_id      INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  object_name    VARCHAR2(30) NOT NULL,
  data           JSON,
  CONSTRAINT object23c_pk PRIMARY KEY (object_id)
);


ALTER TABLE object23c ADD CONSTRAINT object23c_ck1 
  CHECK (data IS JSON VALIDATE q'[{
    "type"       : "object",
    "properties" : {
      "fruit"    : {"type"      : "string",
                    "minLength" : 1,
                    "maxLength" : 10},
      "quantity" : {"type"      : "number",
                    "minimum"   : 0,
                    "maximum"   : 100},
      "orderdate": {"type": "string",
                    "default": "now",
                    "format": "date"}
      }, 
      "required"   : ["fruit", "quantity"]
    }]'
  );

ALTER TABLE object23c DROP CONSTRAINT object23c_ck1;


set pagesize 1000
SELECT json_serialize(DBMS_JSON_SCHEMA.describe('OBJECT23C', null, 'DATA') pretty);


create or replace json relational duality view json23c as
select json { '_id':        {'object_id': o.objecT_id},
              'object_name': o.object_name,
--              'data': o.data,
              unnest(select json { '_id':             {'object_type_id': ot.object_type_id},
                                   'objecT_type_name': ot.objecT_type_name}
                     from   object_type ot 
                     where  o.object_type_id = ot.object_type_id
                   )
            }
from object o 
with insert update delete;


select * from json23c;

SELECT json_serialize(DBMS_JSON_SCHEMA.describe('JSON23C') PRETTY);

SELECT DBMS_JSON_SCHEMA.describe('JSON23C');

